#做成服务注册
server:
  port: 8767

eureka:
  client:
    serviceUrl:
      #            defaultZone: http://localhost:8761/eureka/
      #            docker 部署开启
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

# mysql
spring:
  application:
    name: ace-generator
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ag_auth?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    mode: LEGACYHTML5
    cache: false

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

