server:
  port: 8778

eureka:
  client:
    serviceUrl:
      #            defaultZone: http://localhost:8761/eureka/
      #            docker 部署开启
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

# mysql
spring:
  application:
    name: ace-vod
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/videocms?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    mode: LEGACYHTML5
    cache: false


# Mybatis配置
mybatis:
  configLocation: classpath:/mybatis-config.xml
  mapper-locations: "classpath*:mapper/*.xml"

logging:
  config: classpath:logback-spring.xml

#连接到auth服务鉴权
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

auth:
  serviceId: ace-auth
  user:
    token-header: Authorization
  client:
    id: ace-vod
    secret: vod
    token-header: x-client-token



